### ISSUE TITLE
Login with Offline mode

### ISSUE THREAD

**Issue by iamalper** [woder/TorchBot#22]
I want play on offline server but i cant find a way to login offline.
I leaved password blank but it says
**Authentication failed: Invalid credentials. Invalid username or password.**

**Comment by woder** [comment]
Ah yes, if you are trying to connect to offline server without any valid account it will be troublesome because your username will be blank upon connection. You can actually ignore that authentication error because it won't stop you from connecting to a server, the username issue might however.

We don't really support offline servers, but I can maybe try a patch to make it work if it is just an issue with the username.

**Comment by iamalper** [comment]
But i cant connect any server. It says disconnected from server.
I cant find any info in logs and config.
